// apps/reactapp/src/app/app.tsx
import React from 'react';

import './app.css';

const divStyle = {
  width: '300px'
};

export const App = () => {
  return (
    <>
      <header className="header">
        <div style={divStyle}>
          <a href="http://localhost:4200">
            <img
              src="../assets/angular.png"
              alt="Angular"
              width="40"
              height="40"
            />
          </a>
          <img src="../assets/react.png" alt="React" width="40" height="40" />
        </div>
        <shopping-cart counter={0} />
      </header>
      <div>
        <img src="../assets/react.png" alt="Avatar" width="300" />
        <add-to-cart-button type="React" />
      </div>
    </>
  );
};

export default App;

// apps/angularapp/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'reactangular-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  counter = 0;
  buy(type: CustomEvent) {
    this.counter++;
  }
}

<header class="header">
  <div style="width:300px">
    <img src="../assets/angular.png" alt="Angular" width="40" height="40" />
    <a href="http://localhost:4201">
      <img src="../assets/react.png" alt="React" width="40" height="40" />
    </a>
  </div>
  <shopping-cart [counter]="counter"></shopping-cart>
</header>

<div>
  <img src="../assets/angular.png" alt="Avatar" width="300" />
  <add-to-cart-button
    type="Angular"
    (addToCart)="buy($event)"
  ></add-to-cart-button>
</div>
